TYPO3-Documentation/blog_example

Configuration/TCA/tx_blogexample_domain_model_blog.php, Configuration/TCA/tx_blogexample_domain_model_info.php, Configuration/TCA/tx_blogexample_domain_model_person.php, Configuration/TCA/tx_blogexample_domain_model_post.php, Configuration/TCA/tx_blogexample_domain_model_tag.php
As discussed in the documentation comment, it is better to use the language fields with l10n_ here. 
https://github.com/TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid/pull/392
=> [TASK] Use l10n_ instead of l18n_

Resources/Private/Templates/Post/Index.html
The name of the key doesn't matter, however wrong spelling should be corrected.
=> [TASK] Correct spelling

README.md
This extension now is for TYPO3 11LTS, not for 10LTS anymore,
and the badge should reflect that.
=> [TASK] Adapt the TYPO3 version badge to the used version

composer.json
This extension uses classes from the `typo3fluid/fluid` and hence should
have it as an explicit requirement. (Relying on transitive dependencies
is bad practices as the dependencies' dependencies are allowed to change
without notice.)
=> [BUGFIX] Add `typo3fluid/fluid` as an explicit dependency

composer.json
This allows IDEs like PhpStorm to automatically set the correct
language level.
=> [TASK] Add a PHP version requirement to `composer.json`

Configuration/TCA/tx_blogexample_domain_model_blog.php
This was removed from Core with v10.0:
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.0/Breaking-87193-DeprecatedFunctionalityRemoved.html?highlight=t3ver_label
=> [TASK] Remove t3ver_label

.gitattributes, .gitignore
The `.gitignore` keeps unrelated files out of versioning control,
and the `.gitattributes` keeps development files out of packaging.
=> [TASK] Add `.gitignore` and `.gitattributes`

Resources/Private/Backend/Templates/Blog/New.html
Search results hint that f:form.textbox is gone since TYPO3 v4.7.  This
commit replaces it with f:form.textfield, as suggested in
- https://docs.typo3.org/typo3cms/exceptions/master/en-us/Exceptions/1289386765.html
=> [BUGFIX] Replace long gone f:form.textbox

ext_localconf.php
As the current version of the extension needs at least TYPO3 v12 the check for older version can be removed safely.
Additionally, an unused "use" is dropped.
=> [TASK] Remove superfluous version check

Configuration/TCA/tx_blogexample_domain_model_blog.php
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Deprecation-98479-DeprecatedFileReferenceRelatedFunctionality.html
=> [TASK] Substitute ExtensionManagementUtility::getFileFieldTCAConfig() with TCA file type

.github/workflows/publish.yml, .github/workflows/tests.yml
Additionally, use ubuntu-latest instead of a dedicated version to avoid outdated Ubuntu versions which are not supported anymore by GitHub in the future.
=> [CI] Update actions/checkout to version 4

composer.json
Additionally, to avoid running in validation errors on CI on further updates of the composer-normalize package the version is bound to the minor version. This has then to be adjusted manually.
=> [Backport 12.4] [TASK] Run "composer normalize" in current version (#66)

.github/workflows/tests.yml
Separate linting (different PHP versions) with quality checks (one PHP version). The quality checks need only to run on one version.
This is now in line with the workflow from t3docs/examples.
=> [CI] Streamline tests

composer.json
Now the constraint is in-line with the main branch.
Releases: 12.4
=> [TASK] Update typo3/coding-standards to 0.7.1

.github/workflows/tests.yml, Build/Scripts/runTests.sh, Build/testing-docker/docker-compose.yml
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/781
Releases: main
=> [CI] Run tests on at least PHP 8.2

.php-cs-fixer.dist.php, Classes/Service/BlogFactory.php, composer.json
typo3/coding-standards is not compatible with Symfony 7 (necessary for TYPO3 v13), so we use php-cs-fixer directly instead of relying on another package.
The rules for the php-cs-fixer are the same as for TYPO3 Core.
=> [TASK] Use php-cs-fixer

CHANGELOG.md, Classes/Controller/BackendController.php
This is necessary to be compatible with TYPO3 v13.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/810
Releases: main
=> [TASK] Add return type to BackendController->initializeAction()

CHANGELOG.md, Classes/Controller/PostController.php, Classes/PageTitle/BlogPageTitleProvider.php, Configuration/TypoScript/setup.typoscript
Add class BlogPageTitleProvider for use in the PostController. It outputs the title of the blog in the indexAction and the title of the post in the showAction.
Resolves: https://github.com/TYPO3-Documentation/blog_example/issues/43
=> [FEATURE] Add page title provider for blog (#80)

CHANGELOG.md, Classes/Controller/BlogController.php
=> [BUGFIX] Invoke addFlashMessage() correctly when deleting a blog

Classes/Controller/BlogController.php, Classes/Controller/PostController.php
=> [TASK] Use assignMultiple() where appropriate

Classes/ExpressionLanguage/ExtensionConfigurationProvider.php
While installing t3docs-code-snippets I got error: "No extension configuration for extension blog_example found".
Sure, there is no ext_conf_template.txt file for
blog_extension. But as we need the expression language file for documentation snippets we now wrap that lines with try-catch.
Relates: #103
=> [BUGFIX] Catch error while retrieving extension settings

.github/workflows/tests.yml, Build/Scripts/runTests.sh, Build/phpunit/FunctionalTests.xml, Build/phpunit/FunctionalTestsBootstrap.php, Build/phpunit/UnitTests.xml, Build/phpunit/UnitTestsBootstrap.php, Tests/Functional/DummyTest.php, Tests/Functional/ExtensionTestCase.php, Tests/Unit/DummyTest.php, composer.json
- **[TASK] Require development dependencies correctly**
Some package dependencies have been added as extension
dependencies, albeit being pure development dependencies.
This change requires development dependencies as dev
dependencies now.
Used command(s):
```terminal
Build/Scripts/runTests.sh -p 8.2 -s composer -- \
remove --no-update \
"typo3/cms-install"
Build/Scripts/runTests.sh -p 8.2 -s composer -- \
require --dev --no-update \
"typo3/cms-install":"^13.1 || dev-main"
```
- **[TASK] Add `typo3/testing-framework`**
This change simply adds the `typo3/testing-framework`
along with required dependencies (phpunit) to prepare
towards adding unit and functional tests.
Used command(s):
```terminal
Build/Scripts/runTests.sh -p 8.2 -s composer -- \
require --dev --no-update \ …
```
=> [TASK] Introduce `unit` and `functional` testing infrastructure

ext_emconf.php
In TYPO3 the values from `ext_emconf.php` and `composer.json` will be joined. IMO they are called `Manifest` internally. So, it is not needed anymore to add autoloader information to `ext_emconf.php` since TYPO3 ~6.2.13.
=> Remove autoloader from ext_emconf.php

Classes/Domain/Validator/TitleValidator.php, Tests/Unit/Domain/Validator/TitleValidatorTest.php
The method `isValid` allows `mixed` types of properties. That's why I have added a check for valid data types before processing with `str_starts_with`.
Further there was a huge mistake in `TitleValidator`. The `$needle` and `$haystack` arguments were miss-matched! Thanks to UnitTests for finding that.
=> Add unit test for TitleValidator

Configuration/Sets/BlogExample/page.tsconfig
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.0/Breaking-102834-RemoveItemsFromNewContentElementWizard.html#impact
Nevertheless two of the listed plugins were invalid
=> Remove 'show' from page TSconfig as not evaluated anymore

Classes/Controller/BlogController.php, Classes/Controller/PostController.php, Configuration/FlexForms/PluginSettings.xml, Configuration/TCA/Overrides/tt_content.php
Merge 1st
Load FlexForm `PluginSettings.xml` if plugin `blogexample_bloglist` was selected. Previously it was only loaded on plugin `blogexample_postlist`, but that plugin seems to be removed in earlier patches.
Change `settings.postsPerPage` to `settings.itemsPerPage` as we have two paginators in blog_example. I don't want to create two items `blogsPerPage` and `postsPerPage` as I'm pretty sure that FlexForm is included in Docs as an example somewhere.
Make use and cast value of `settings.itemsPerPage` to int in `BlogController` and `PostController`, but keep 3 as default as fallback.
=> Repair usage of FlexForm PluginSettings.xml

Build/rector/rector.php, Classes/ViewHelpers/GravatarViewHelper.php, Resources/Private/Templates/Post/Show.html, ext_emconf.php
See also: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/4735
References: TYPO3-Documentation/Changelog-To-Doc#1008
=> [Deprecation] renderStatic() for Fluid ViewHelpers
