TYPO3-Documentation/blog_example

Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf

add settings.editorUsergroupUid

---

README.md
composer.json

Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/182

[TASK] Align with new TYPO3 documentation standards

---

Classes/Controller/AbstractController.php
Classes/Controller/BlogController.php
Classes/Controller/CommentController.php
Classes/Controller/PostController.php
Classes/Domain/Model/Administrator.php
Classes/Domain/Model/Blog.php
Classes/Domain/Model/Comment.php
Classes/Domain/Model/Info.php
Classes/Domain/Model/Person.php
Classes/Domain/Model/Post.php
Classes/Domain/Model/Tag.php
Classes/Domain/Repository/AdministratorRepository.php
Classes/Domain/Repository/BlogRepository.php
Classes/Domain/Repository/PersonRepository.php
Classes/Domain/Repository/PostRepository.php
Classes/Domain/Validator/BlogValidator.php
Classes/Domain/Validator/PostValidator.php
Classes/ExpressionLanguage/ExtensionConfigurationProvider.php
Classes/Service/BlogFactory.php
Classes/ViewHelpers/GravatarViewHelper.php

This is a pre-patch in order to keep unrelated changes out of the
upcoming type declaration cleanup.

[TASK] Autoformat the class files

---

Classes/Controller/AbstractController.php
Classes/Controller/BlogController.php
Classes/Controller/CommentController.php
Classes/Controller/PostController.php
Classes/Domain/Model/Administrator.php
Classes/Domain/Model/Blog.php
Classes/Domain/Model/Comment.php
Classes/Domain/Model/FrontendUserGroup.php
Classes/Domain/Model/Info.php
Classes/Domain/Model/Person.php
Classes/Domain/Model/Post.php
Classes/Domain/Model/Tag.php
Classes/Domain/Repository/AdministratorRepository.php
Classes/Domain/Repository/BlogRepository.php
Classes/Domain/Repository/PersonRepository.php
Classes/Domain/Repository/PostRepository.php
Classes/Domain/Validator/BlogValidator.php
Classes/Domain/Validator/PostValidator.php
Classes/Service/BlogFactory.php
Classes/ViewHelpers/GravatarViewHelper.php

Also drop redundant comments and type annotations.

[TASK] Use more native type declarations

---

.gitignore
CHANGELOG.md
Classes/Controller/CommentController.php
Classes/Domain/Model/Comment.php
Classes/Property/TypeConverters/HiddenCommentConverter.php
Configuration/Services.yaml

based on https://in2code.de/aktuelles/hidden-objects-an-extbase-actions-uebergeben/
resolves #34
references TYPO3-Documentation/Changelog-To-Doc#8

[FEATURE] Add TypeConverter Examples

---

Classes/Domain/Validator/BlogValidator.php
Classes/Domain/Validator/PostValidator.php
Classes/Domain/Validator/TitleValidator.php
Classes/Service/BlogValidationService.php
Classes/Service/PostValidationService.php

references https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/94
resolves #36

[TASK] Add Dependency Injection as example to the Validators

---

composer.json
ext_emconf.php

[TASK] Set compatibility to TYPO3 v12.4 only

---

composer.json
ext_emconf.php

[TASK] Set compatibility to TYPO3 v13/main only

---

.github/workflows/backport.yml

[CI] Add backport workflow

---

Classes/Domain/Model/Blog.php
Classes/Domain/Model/Post.php

[TASK] Fix CGL after update to php-cs-fixer v3.26.1

---

Resources/Private/Language/Module/locallang_mod.xlf
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf

- Set "original" attribute to file name.
- Add missing "resname" attributes
- Remove superfluous "xml:space" and "approved" attributes

[TASK] Streamline XLIFF files

---

Classes/Controller/PostController.php

[BUGFIX] Correct method call when building ForwardReponse

---

.php-cs-fixer.dist.php
Classes/Controller/AbstractController.php
Classes/Controller/BackendController.php
Classes/Controller/BlogController.php
Classes/Controller/CommentController.php
Classes/Controller/PostController.php
Classes/Domain/Repository/PostRepository.php
Classes/Domain/Validator/BlogValidator.php
Classes/Property/TypeConverters/HiddenCommentConverter.php
Configuration/TCA/Overrides/sys_template.php
Configuration/TCA/Overrides/tt_content.php
ext_localconf.php

[TASK] Set more options for php-cs-fixer's trailing comma in multiline rule

---

composer.json

[TASK] Update dev dependencies

---

CHANGELOG.md
Classes/Controller/PostController.php

[BUGFIX] Invoke addFlashMessage() correctly when deleting a post

---

CHANGELOG.md

[DOCS] Add release date for version 12.1.0

---

.gitignore
.php-cs-fixer.dist.php
Classes/Controller/BackendController.php
Classes/Controller/BlogController.php
Classes/Controller/PostController.php
Classes/Domain/Model/Blog.php
Classes/Domain/Repository/CommentRepository.php
Classes/Domain/Validator/BlogValidator.php
Classes/Domain/Validator/PostValidator.php
Configuration/TCA/tx_blogexample_domain_model_blog.php
Configuration/TCA/tx_blogexample_domain_model_comment.php
Configuration/TCA/tx_blogexample_domain_model_info.php
Configuration/TCA/tx_blogexample_domain_model_person.php
Configuration/TCA/tx_blogexample_domain_model_post.php
Configuration/TCA/tx_blogexample_domain_model_tag.php
Makefile
README.md
composer.json
ext_emconf.php
rector.php

[TASK] Allow TYPO3 v13

---

composer.json

[TASK] Remove outdated replace from composer.json

---

Configuration/Sets/BlogExample/page.tsconfig
Configuration/TCA/Overrides/tt_content.php
ext_conf_template.txt
ext_localconf.php

Remove pi1 plugin
resolves https://github.com/TYPO3-Documentation/blog_example/issues/44 releases: main

[TASK] Consolidate plugins

---

Classes/Domain/Model/Blog.php
Classes/Service/BlogValidationService.php

[BUGFIX] Prevent type errors if subtitle is not set

---

Makefile

[TASK] Run all tests with make

---

Tests/Unit/Domain/Model/TagTest.php

Moved from https://github.com/TYPO3-Documentation/blog_example/pull/106

Add unit tests for tag model

---

Classes/Domain/Model/Blog.php
Classes/Domain/Model/FrontendUser.php
Classes/Domain/Model/FrontendUserGroup.php
Classes/Domain/Model/Info.php
Classes/Domain/Model/Person.php
Classes/Domain/Model/Post.php

Make objectstorages nullable to prevent https://docs.typo3.org/m/typo3/reference-exceptions/main/en-us/Exceptions/1546632293.html

[TASK] Move object storage initialization to initializeObject

---

Classes/Controller/BackendController.php

Redirect to index action if blog is not found
Show flash message when blog was deleted
Extract popoulate button to its own method

[TASK] Refactor Backend Controller

---

Configuration/TCA/Overrides/tt_content.php
Resources/Private/Language/locallang_db.xlf

Merge 2nd
This is a pre-patch for the patch to migrate the blog plugins to CType. So, merge that first.

Add new group 'blog' for content element wizard

---

Configuration/TCA/tx_blogexample_domain_model_blog.php
Configuration/TCA/tx_blogexample_domain_model_comment.php
Configuration/TCA/tx_blogexample_domain_model_info.php
Configuration/TCA/tx_blogexample_domain_model_person.php
Configuration/TCA/tx_blogexample_domain_model_post.php
Configuration/TCA/tx_blogexample_domain_model_tag.php
composer.json

Raise dependencies to 13.3 as this did not work before.
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/967
Releases: main

[FEATURE] Add default TCA columns from ctrl

---

.github/workflows/tests.yml
Build/Scripts/runTests.sh
Classes/Controller/BackendController.php

[CI] Lint code with PHP 8.4

---

Build/phpunit/FunctionalTestsBootstrap.php
Build/phpunit/UnitTestsBootstrap.php

[BUGFIX] Run cgl fixer

---

Resources/Private/Language/Module/locallang_mod.xlf
Resources/Private/Language/de.locallang.xlf
Resources/Private/Language/locallang.xlf
Resources/Private/Language/locallang_db.xlf

References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/1167
Releases: main

[TASK] Get rid of "resname" attribute in XLF files

---

Build/Scripts/runTests.sh

Update MariaDB version to 10.11

Update MariaDB version for func. tests

---

Classes/Controller/PostController.php

[BUGFIX] Use proper view variable assignment

---

Classes/Controller/CommentController.php

https://github.com/TYPO3-Documentation/blog_example/issues/163

Rename publishAction initialization method
